### ISSUE TITLE
Add list of nearby hotels to sprint website and wiki page

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/dev-ogc-org-sprint-landing-20#4]

**Comment by ghobona** [comment]
[HotelsLausanne.pdf](https://github.com/opengeospatial/dev-ogc-org-sprint-landing-20/files/10991433/HotelsLausanne.pdf)

**Comment by doublebyte1** [comment]
https://github.com/opengeospatial/dev-ogc-org-sprint-landing-20/commit/7546716d33b93673f769976968ffc1dface0007d
